import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { supabase } from '../lib/supabaseClient'

export default function Mesas({res}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Listado de mesas:</h1>
        <div>{JSON.stringify(res, null, 2)}</div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export async function getStaticProps () {
    let { data: res, error } = await supabase.from('rest_mesas').select('*')
    return {
        props: {
            res
        }
    }
  }
  
